"""empty message

Revision ID: 0fe63ecf74d3
Revises: 3bed590b7848
Create Date: 2021-04-27 17:07:43.492848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe63ecf74d3'
down_revision = '3bed590b7848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
