"""empty message

Revision ID: 14419ed3afe2
Revises: 
Create Date: 2021-05-13 14:28:37.634832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '14419ed3afe2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('childCategories', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('category', sa.Column('parentCategory', sa.String(length=200), nullable=True))
    op.drop_column('category', 'subsetList')
    op.drop_column('category', 'image')
    op.drop_column('category', 'description')
    op.drop_column('category', 'viewed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('viewed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('category', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('category', sa.Column('image', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('category', sa.Column('subsetList', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('category', 'parentCategory')
    op.drop_column('category', 'childCategories')
    # ### end Alembic commands ###
