"""empty message

Revision ID: 191439ea12db
Revises: de686bdabac4
Create Date: 2021-05-03 00:47:20.462447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191439ea12db'
down_revision = 'de686bdabac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'categoryId',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.create_index(op.f('ix_category_title'), 'category', ['title'], unique=False)
    op.drop_column('category', 'id')
    op.alter_column('product', 'productId',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.create_index(op.f('ix_product_title'), 'product', ['title'], unique=False)
    op.drop_column('product', 'id')
    op.alter_column('shop', 'shopId',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.create_index(op.f('ix_shop_title'), 'shop', ['title'], unique=False)
    op.drop_column('shop', 'id')
    op.alter_column('user', 'userId',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.alter_column('user', 'userId',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.add_column('shop', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_shop_title'), table_name='shop')
    op.alter_column('shop', 'shopId',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.add_column('product', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_product_title'), table_name='product')
    op.alter_column('product', 'productId',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.add_column('category', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_category_title'), table_name='category')
    op.alter_column('category', 'categoryId',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
