"""empty message

Revision ID: 221cfa5c1012
Revises: 76ca0ae57664
Create Date: 2021-05-24 00:52:31.892760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '221cfa5c1012'
down_revision = '76ca0ae57664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('imageList', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('product', sa.Column('ifPublished', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'ifPublished')
    op.drop_column('category', 'imageList')
    # ### end Alembic commands ###
