"""empty message

Revision ID: 48daef4fc5f9
Revises: 0fe63ecf74d3
Create Date: 2021-04-27 22:48:56.448390

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48daef4fc5f9'
down_revision = '0fe63ecf74d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('address', sa.String(length=10), nullable=True))
    op.add_column('shop', sa.Column('bankAcountsInformation', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('shop', sa.Column('customersList', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('shop', sa.Column('phoneNumber', sa.String(length=13), nullable=True))
    op.add_column('shop', sa.Column('productsList', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('shop', sa.Column('shopLink', sa.String(length=200), nullable=True))
    op.drop_column('shop', 'ifUsed')
    op.drop_column('shop', 'city')
    op.drop_column('shop', 'ordered')
    op.drop_column('shop', 'byer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('byer', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('shop', sa.Column('ordered', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('shop', sa.Column('city', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('shop', sa.Column('ifUsed', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('shop', 'shopLink')
    op.drop_column('shop', 'productsList')
    op.drop_column('shop', 'phoneNumber')
    op.drop_column('shop', 'customersList')
    op.drop_column('shop', 'bankAcountsInformation')
    op.drop_column('shop', 'address')
    # ### end Alembic commands ###
