"""empty message

Revision ID: 76ca0ae57664
Revises: 1b5ffff75567
Create Date: 2021-05-22 13:43:45.789056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ca0ae57664'
down_revision = '1b5ffff75567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('categoryName', sa.String(length=200), nullable=True))
    op.add_column('product', sa.Column('shopName', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'shopName')
    op.drop_column('product', 'categoryName')
    # ### end Alembic commands ###
