"""empty message

Revision ID: 8ab9cde72021
Revises: a4750d3a747b
Create Date: 2021-05-04 01:29:36.218802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ab9cde72021'
down_revision = 'a4750d3a747b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shop_owner', table_name='shop')
    op.drop_index('ix_shop_shopId', table_name='shop')
    op.drop_index('ix_shop_title', table_name='shop')
    op.drop_table('shop')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('shopId', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('createdDatetime', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('modified_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('imageList', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phoneNumber', sa.VARCHAR(length=13), autoincrement=False, nullable=True),
    sa.Column('productsList', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('customersList', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('bankAcountsInformation', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('viewed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shopLink', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('shopId', name='shop_pkey')
    )
    op.create_index('ix_shop_title', 'shop', ['title'], unique=False)
    op.create_index('ix_shop_shopId', 'shop', ['shopId'], unique=True)
    op.create_index('ix_shop_owner', 'shop', ['owner'], unique=False)
    # ### end Alembic commands ###
