"""empty message

Revision ID: 9973228889a8
Revises: 0b25ff7c1c67
Create Date: 2021-06-06 13:39:14.764620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9973228889a8'
down_revision = '0b25ff7c1c67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_archive', sa.Column('deletedDatetime', sa.String(length=20), nullable=True))
    op.add_column('product_archive', sa.Column('deletedDatetime', sa.String(length=20), nullable=True))
    op.add_column('shop_archive', sa.Column('deletedDatetime', sa.String(length=20), nullable=True))
    op.add_column('user_archive', sa.Column('deletedDatetime', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_archive', 'deletedDatetime')
    op.drop_column('shop_archive', 'deletedDatetime')
    op.drop_column('product_archive', 'deletedDatetime')
    op.drop_column('category_archive', 'deletedDatetime')
    # ### end Alembic commands ###
