"""empty message

Revision ID: de686bdabac4
Revises: 
Create Date: 2021-05-01 00:55:27.650364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de686bdabac4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_productId_key', 'product', type_='unique')
    op.create_index(op.f('ix_product_owner'), 'product', ['owner'], unique=False)
    op.create_index(op.f('ix_product_productId'), 'product', ['productId'], unique=True)
    op.drop_constraint('shop_shopId_key', 'shop', type_='unique')
    op.create_index(op.f('ix_shop_owner'), 'shop', ['owner'], unique=False)
    op.create_index(op.f('ix_shop_shopId'), 'shop', ['shopId'], unique=True)
    op.create_index(op.f('ix_user_userId'), 'user', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_userId'), table_name='user')
    op.drop_index(op.f('ix_shop_shopId'), table_name='shop')
    op.drop_index(op.f('ix_shop_owner'), table_name='shop')
    op.create_unique_constraint('shop_shopId_key', 'shop', ['shopId'])
    op.drop_index(op.f('ix_product_productId'), table_name='product')
    op.drop_index(op.f('ix_product_owner'), table_name='product')
    op.create_unique_constraint('product_productId_key', 'product', ['productId'])
    # ### end Alembic commands ###
